### ISSUE TITLE
fhem crashed after a while and couldn't start again

### ISSUE THREAD

**Issue by lke15** [unimatrix27/fhemmodules#1] opened 2017-01-04 12:25 UTC
After creating a device I can control the snapserver/clients. When i restart fhem it didn't start again.
With verbose 5 it gives follow log:

```
2017.01.04 13:13:50 5: Loading ./FHEM/96_Snapcast.pm
2017.01.04 13:13:50 1: PERL WARNING: Scalar value @values[$i] better written as $values[$i] at ./FHEM/96_Snapcast.pm line 324, <$fh> line 1959.
2017.01.04 13:13:50 1: PERL WARNING: Scalar value @values[$i+1] better written as $values[$i+1] at ./FHEM/96_Snapcast.pm line 325, <$fh> line 1959.
2017.01.04 13:13:50 3: Opening snap device xxxxxxx:1705
2017.01.04 13:13:50 3: {"jsonrpc":"2.0","id":1,"method":"Server.GetStatus"}

2017.01.04 13:13:50 5: SW: 7b226a736f6e727063223a22322e30222c226964223a312c226d6574686f64223a225365727665722e476574537461747573227d0d0a
```
The only way to get run fhem is, when i delete the snapcast device from fhem.cfg

**Comment by unimatrix27** [comment] 2017-01-11 07:16
I did a lot of cleanup and fixing of some bugs yesterday, so I would appreciate if you could try out the newest version and please let me know if it works. Thanks!

**Comment by lke15** [comment] 2017-01-11 08:02
I've installed yesterday the new version. Today fhem did not run anymore. The last line in fhem.log was:

malformed JSON string, neither array, object, number, string or atom, at character offset 1448 (before "(end of string)") at ./FHEM/96_Snapcast.pm line 498.

But I must say actually I use the snapcast develop branch

**Comment by unimatrix27** [comment] 2017-01-11 09:11
The modul is not yet working with the develop branch, because there are some significant changes in the JSON structure that the author is still working on, so I will implement them as soon as this is done. 

In any case, FHEM should not die, so I hope the problem is fixed now. In case an invalid JSON is received from snapcast, it will be mentioned in the log.

**Comment by lke15** [comment] 2017-01-11 09:21
That's right. I've seen that the groups are not work. At the time as I open the ticket, I use the master branch of snapcast.

**Comment by unimatrix27** [comment] 2017-01-11 09:28
Understood, please let me know if the fix solves the problem and feel free to post your log output.

**Comment by lke15** [comment] 2017-01-11 10:55
I've test it again with follow conditions:
- current git version of 96_snapcast.pm
- current master branch of snapcast
- snapserver runs
- fhem runs without snapcast defined

Proceeding:
- Define a Snapcast device in fhem
- Save fhem config
- Restart fhem

Result:
After define the snapcast device the server infos was shown in fhem. Everythink ok.
Now i make a shutdown restart in fhem, and fhem hangs while the startup process. 
After some minutes fhem doesn't start.

Last lines in fhem.log
`
2017.01.11 11:46:04 3: Opening snap device 172.xxxxx.30:1705
2017.01.11 11:46:04 3: {"jsonrpc":"2.0","id":1,"method":"Server.GetStatus"}

2017.01.11 11:46:04 5: SW: 7b226a736f6e727063223a22322e30222c226964223a312c226d6574686f64223a225365727665722e476574537461747573227d0d0a
`

tcpflow on mpd board:
`172.xxxxx.001.52115-172.xxxxx.030.01705: {"jsonrpc":"2.0","id":1,"method":"Server.GetStatus"}

172.xxxxx.030.01705-172.xxxxx.001.52115: {"id":1,"jsonrpc":"2.0","result":{"clients":[],"server":{"host":{"arch":"armv7l","ip":"","mac":"","name":"mpd","os":"Debian GNU/Linux 8.2 (jessie)"},"snapserver":{"controlProtocolVersion":1,"name":"Snapserver","protocolVersion":1,"version":"0.10.0"}},"streams":[{"id":"default","status":"idle","uri":{"fragment":"","host":"","path":"/tmp/snapfifo","query":{"buffer_ms":"20","codec":"flac","name":"default","sampleformat":"48000:16:2"},"raw":"pipe:///tmp/snapfifo?name=default","scheme":"pipe"}}]}}`

I killed the fhem process, removed the define from fhem.cfg, fhem start without problems.

**Comment by unimatrix27** [comment] 2017-01-11 11:26
This was actually a different problem, I missed to include a check during startup. Should work now. Thanks for the feedback.

**Closed as completed** 2017-01-11 11:26 UTC
Labels: bug

**Comment by lke15** [comment] 2017-01-11 12:51
Yes, i can confirm it, too. The restart works.
